// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef WC_MainWindow_h
#define WC_MainWindow_h
#include <FL/Fl.H>
#undef WC_MainWindow_h
namespace EE604A {namespace GUI {class WC_MainWindow;}}; 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Box.H>

class EE604A::GUI::WC_MainWindow : public Fl_Double_Window {
  void _WC_MainWindow();
public:
  WC_MainWindow(int X, int Y, int W, int H, const char *L = 0);
  WC_MainWindow(int W, int H, const char *L = 0);
  WC_MainWindow();
  static Fl_Menu_Item menu_[];
protected:
  Fl_Box *wImageBox1;
  Fl_Box *wImageBox2;
private:
  virtual void WOpen_cb (void) {}; 
  virtual void WQuit_cb (void) {}; 
};
#endif
